### ISSUE TITLE
Make "Style information" a separate resource

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-styles#1]
Comment from a participant in the OGC Vector Tiles Pilot 2:

> I would like to highlight again my strong preference for styles being a link to a resource listing only styles, not being embedded directly in the collections, because it is part of the modular Styles API, and there could be a great number of styles X encodings in there.

The proposal is to include the style information in a separate resource under the collection resource (e.g., `/collections/{collectionId}/styles`) instead of including it in the collection resource itself.

**Comment by jeffharrison** [comment]
Sounds reasonable.

Best Regards,
Jeff
