### ISSUE TITLE
What is the style recommended or the default style?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-styles#15]
Can we add property in .../{collectionID}/styles to define the "favorite" style or the "default" style in a collection?

**Comment by jeffharrison** [comment]
SWG discussed this Issue on June 1 2021. Consensus is it makes sense to be able to specify a "default" style in a collection.

API must allow a "manager' to change the default style. Accordingly, need a simple mechanism to update default style via API. 

Clemens P will develop draft for SWG review.
