### ISSUE TITLE
metadata about styles "link" "rel" 

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-styles#17]
The specification says "Each style SHALL have a link to the style metadata (link relation type: describedby) with the type attribute stating the media type of the metadata encoding."
Tis is not consistent with the Features API to retrieve the schema of the dataset From a Features API example: "An additional link is to a GML application schema for the dataset - using link relation type "describedBy".". Recently in OGC-API common we agreed on "data-meta" for "metadata".

Can we use "data-meta" here too?.

**Comment by cportele** [comment]
I do not see a good reason for using an OGC-specific link relation type where the IANA-registered `describedby` fits.

I do not see any inconsistency with OGC API Features.

In addition, considering a style to be data seems like a stretch.
