### ISSUE TITLE
Correct the full URLs rels to lowercase.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-styles#18]
http://www.opengis.net/def/rel/OGC/1.0/

should be

http://www.opengis.net/def/rel/ogc/1.0/

the first one is not resolvable.

**Comment by cportele** [comment]
@joanma747 - Thanks for pointing this out, I will fix this today. I guess I am just to used to "OGC" as the authority from the CRS register, but in the link relations the authority is "ogc" (which I prefer).
