### ISSUE TITLE
Proposal to use "rel" : "style" rather than style sheet, with ?f= or Accept-Encoding selecting sheet through media type, and results in an actual style resource

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-styles#2]
Implementation example @ http://maps.ecere.com/geoapi/collections/vtp/Daraa2/styles?f=json

http://maps.ecere.com/geoapi/collections/vtp/Daraa2/styles/newNight

is an actual style resource with multiple style sheets (one per supported encoding).

**Comment by jeffharrison** [comment]
Thanks Jerome!

Best Regards,
Jeff

**Comment by jeffharrison** [comment]
This Issue has been "overcome by events". SWG recommended closing on 20 Apr.

**Comment by jerstlouis** [comment]
We have adopted the `stylesheet` rel to link to the actual style sheet representation (e.g. SLD/SE, MapboxGL, CMSS) in our implementation. (Updated end-point: http://maps.ecere.com/ogcapi/collections/Daraa/styles?f=json)

This still allows to have one single style resource supporting multiple encodings selected through content negotiation.
No longer sure whether there ever was an issue or not.
