### ISSUE TITLE
Styles, Tiles: Metadata review

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-styles#39]
There is significant overlap between the metadata for a [style](https://docs.ogc.org/DRAFTS/20-009.html#req_core_style-md-success) and for a [tileset](https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/schemas/tms/2.0/json/tileSet.json). At the same time, there are issues and differences that should be addressed. And then there are the [core queryables from Records](https://docs.ogc.org/DRAFTS/20-004.html#core-queryables-resource-table).

* "title" and "version" are the same.
* "abstract" vs "description". Proposal: use "description. See opengeospatial/ogcapi-code-sprint-2021-05#31.
* "keywords": Styles uses strings, Tiles a more complex model. Note that Records uses strings for "keywords", too. For controlled vocabularies, "themes" is used. Proposal: restrict "keywords" to strings.
* Styles and Tiles use "pointOfContact", Records uses "contactpoint". Proposal: agree on a single name.
* Styles and Tiles use "accessConstraints" with a fixed list from the intelligence domain. At the same time more generally useful information like "license" is missing. Proposal: add "license" and drop "accessConstraints" (I think this does not belong into Core and communities that need it can always add it).
* Tiles has "publisher", Styles not. Records has it, too. Proposal: add "publisher" to Styles.
* Styles has a fixed "scope" (value "style"), Tiles has no "scope". Records instead has "type", a URI. Proposal: harmonize.
* Styles has various dates in "dates", Tiles in "date". Records only has "created" and "updated", but not embedded in a data type. Proposal: Follow the approach from Records. It is not clear to me where "validTill" or "receivedOn" are really useful for a style or tileset.
* Styles and Tiles both have "layers", but with different content.
  * "abstract" vs "description". Proposal: use "description. See opengeospatial/ogcapi-code-sprint-2021-05#31.
  * Styles has "type" (point, line, polygon, geometry, raster), Tiles has "dataType" (vector, coverage, map) and "geometryType" (points, lines, polygons). Proposal: use "dataType" and "geometryType".
  * Styles has "attributes" (the OpenAPI 3.0 schema for each attribute), Tiles has "propertiesSchema" (a subset of JSON Schema describing an object where each attribute is a property plus some extensions to JSON Schema like "observedProperty" or "uom"). Proposal: Use standard JSON Schema without restrictions. Add a recommendation for a profile, similar to the approach taken by Features for Queryables. 

In addition, there are additional properties that are specific to the resource. 

Additional comments on the tileset-specific extensions: 

* I find the fact that one can specify scaleDenominator, cellSize and/or the tileMatrix confusing. So every client has to be able to handle all of them and convert them to the internal mechanism that the client uses. Why not pick one to make it easier for clients?
* There is "mediaType" as a string, but the description implies that there can be multiple media types. Should this be an array?

**Comment by cportele** [comment]
@ghobona - Yes, I think we can.

**Comment by ghobona** [comment]
Done, thanks.
