### ISSUE TITLE
3D

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-styles#4]
Raised during the 2020-05-13 Portrayal DWG meeting: Is anything in the current draft limited to 2D or is 3D supported (if there is a style encoding that supports 3D, too)?

**Comment by chris-little** [comment]
@cportele Thank you for adding this issue. The simple kind of use case that I envisage using this API in 3D is a Mission Rehearsal Simulation, or Multi-player Game, or some other Virtual Reality application.
One player sees a perspective view of a 3D scene/environment/world in visible light. Another player is 'using' night goggles, so they see a, possibly different perspective, view of the same 3D scene containing the same objects and players, but in infra-red.
I considered that these two 'views' have different styles. Either player could easily add or remove their night goggles and revert to the other 'style' of view.

**Comment by jeffharrison** [comment]
@cportele I don't believe there is anything in the current draft limited to 2D. A style encoding, whether 2D or 3D, is a resource.

3D style encodings are likely to become very important in coming years... 

Best Regards,
Jeff

**Comment by cportele** [comment]
@jeffharrison - In general, I agree, but I think that in a few places there is an underlying 2d assumption. For example, the style metadata schema knows about points/lines/polygons, but not solids. Nevertheless, these issues will be easy to fix in a careful read of the document.

**Comment by jeffharrison** [comment]
@cportele Right. I was thinking API... need more coffee ;-)

Probably a good fix to make. I'm guessing updating the style metadata schema etc so it doesn't preclude 3D can be handled under this issue...

Best Regards,
Jeff

**Comment by jeffharrison** [comment]
Clemens took the action to work this at Styles SWG mtg...

**Comment by jeffharrison** [comment]
In general, a Styles API should be applicable to both 2D and 3D geospatial content.  It may be possible to remove 'controlled values' from Styles Metadata and Styles API may be able to support multiple 'Ds'.  Recommend this Issue be quickly assessed during Tiles, Maps and Styles Sprint in late May.

SWG also recommends a potential 3D GeoVolumes SWG also assess this.
