### ISSUE TITLE
Requirement Class OGC Styles & Symbology

### ISSUE THREAD

**Issue by KaiVolland** [opengeospatial/ogcapi-styles#45]
Hi :wave:,

The [current draft](https://docs.ogc.org/DRAFTS/20-009.html#rc_sld-10) includes requirement classes for SLD 1.0, SLD 1.1 and Mapbox Styles.

Will there be a requirement class for the https://github.com/opengeospatial/styles-and-symbology too?
And if yes, will there be a a distinction between the CCSSS and JSON encoding?

**Comment by cportele** [comment]
Hi @KaiVolland,

once the standard progresses and implementations are available, I am sure that these style encodings will be added (as separate requirements classes).

Eventually there should be (registered) media types for both encodings.

**Comment by KaiVolland** [comment]
Ok nice. Thank you.
