### ISSUE TITLE
Harmonize the Queryables resource schema across OGC API specs

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-styles#6]
See https://github.com/opengeospatial/ogcapi-features/issues/424

**Comment by cportele** [comment]
PR #10 removes the queryables resource from Styles. It is up to the data source standards (in particular Features, Tiles, Coverages) to specify how schema information about the data can be retrieved. For Features, for example, see https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/schemas.

**Comment by jeffharrison** [comment]
SWG agreed to close this Issue on 4 May 2021. NOTUC.
